### ISSUE TITLE
minimum specs missing

### ISSUE THREAD

**Issue by anuj-rt** [cmusatyalab/elijah-openstack#4]
I  tried deploying this on a machine with 16 GB RAM, 64 GB HDD and 16 VCPUs. The caching takes up 9 GB of RAM space and the rest is used by openstack. The instance goes into "ERROR 500: No host found" state. I found it difficult to figure out what the exact requirements are for the VM to be successfully booted up. Till now, I have tried the setup almost 5-10 times and this led me to figure out that the VM itself requires a huge amount of memory. I am still not sure what the exact requirement is, if it can be specified, it would be really helpful. I am able to launch instances using other images, but the image provided in installation guide doesn't work for me. I am using ubuntu 14.04 and Devstack's kilo release as specified.

**Comment by ronisblogs** [comment]
You can check the detail error messages by viewing the n-sch.log. The following is the error msg I ever got when I tried to install openstack on Xen:
_2015-11-09 13:18:41.943 DEBUG nova.scheduler.filters.disk_filter [req-0d758a1b-9f84-4fda-8d99-4add033dc9a8 admin admin] (DevStackOSDomU, XEN01) ram:32210 disk:-1503232 io_ops:0 instances:0 does not have 1024 MB usable disk, it only has **-1503232.0** MB usable disk. from (pid=12354) host_passes /opt/stack/nova/nova/scheduler/filters/disk_filter.py:60
2015-11-09 13:18:41.943 INFO nova.filters [req-0d758a1b-9f84-4fda-8d99-4add033dc9a8 admin admin] Filter DiskFilter returned 0 hosts_

**Comment by krha** [comment]
Hi @anuj-rt ,

First of all, please use http://forum.openedgecomputing.org/ to the following questions. We are moving our codebase to Open Edge Computing, and the forum is the place for the discussion.

  > The caching takes up 9 GB of RAM space and the rest is used by openstack. 

I just double checked my VM instance, but the VM memory usage is normal at my setup. I guess some other factors affect to your case, but it's hard to what's the problem with the information you provided.

So, let's go step by step. Please first try https://github.com/cmusatyalab/elijah-provisioning/. This is a standalone version of code that shares same library with OpenStack++. If this works well, we can narrow down the problem to the OpenStack related part. Again, for the following discussion, please use the forum. Thank you.
