### ISSUE TITLE
Upgrading from Kilo version of OpenStack to Newton version

### ISSUE THREAD

**Issue by kairen** [cmusatyalab/elijah-openstack#9]
Recently, I upgrading the Elijah-openstack from Kilo version to [Newton version](https://github.com/kairen/elijah-openstack/tree/newton-dev), some function already completed, and testing on devStack Newton. Can help me to create a branch of Github, I will pull a some request to this repository.

**Comment by kairen** [comment]
Anyone can help me?

**Comment by teiszler** [comment]
Apologies for missing this Kyle. So I see you have a fork, newton-dev where you have made some changes towards a Newton version. Are you asking me to create a branch for you to issue the pull request against?

**Comment by teiszler** [comment]
I created a newton-dev branch off of master. Feel free to issue the pull request to that branch.

**Comment by kairen** [comment]
@teiszler , thank for your reply! i pull a request into newton-dev branch at once.
